spring:
  #oracle configure
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/twoapes?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=true
    username: twoapes
    password: 1
    #mongodb database configure
  data:
    mongodb:
      database: twoapes
      host: 127.0.0.1
      port: 1
      username: twoapes
      password: 1