spring:
  #oracle configure
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306?serverTimezone=GMT%2B8&characterEncoding=utf8mb4&useSSL=true
    username: twoapes
    password: 1
  #mongodb configure
  data:
    mongodb:
      database: twoapes
      host: 127.0.0.1
      port: 1
      username: twoapes
      password: 1
#sftp configure
sftp:
  sftpHost: 127.0.0.1
  sftpUserName: twoapes
  sftpPassword: 1
  sftpPort: 1
  sftpPrivateKey: null
#machine configure
machine:
  id: 1
  secret: 1
  key: 1