spring:
  #oracle configure
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:oracle:thin:@127.0.0.1:1521:twoapes
    username: twoapes
    password: 1
  #mongodb configure
  data:
    mongodb:
      database: twoapes
      host: 127.0.0.1
      port: 1
      username: twoapes
      password: 1